### ISSUE TITLE
Term issue: proposed obsoletion: protein-containing material entity

### ISSUE THREAD

**Issue by cmungall** [PROconsortium/PRoteinOntology#307]
I propose obsoleting the following term:

```yaml
id: PR:000050567
name: protein-containing material entity
def: "A material entity that minimally consists of a protein." []
synonym: "protein" NARROW []
synonym: "protein aggregate" NARROW []
synonym: "protein complex" NARROW []
synonym: "protein-containing complex" NARROW []
relationship: has_part PR:000000001
is_a: BFO:0000040
intersection_of: BFO:0000040
intersection_of: BFO:0000051 PR:000000001
```

rationale:

- the extent of the class is outside the scope of PRO, encompassing organs, organisms, a chunk of soil, a building, the Atlantic ocean, the biosphere, the universe
- there is no documented use case for it
- the synonyms are incorrect (even when marked with NARROW).
- (main reason) this causes ragged incomplete lattices when PR is imported

The last (main) point deserves some explanation. When a module is extracted from PRO using SLME this class is typically included, and then after reasoning some classes may be classified here based on has-part relationships; however, this classification is always massively incomplete, as well as being flat and confusing

For example, in CL, there is a giant flat list of arbitrary terms under this:

https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPR_000050567

the arbitrariness can be seen if we focus on two terms, say, neuron and mast cell:

<img width="593" alt="image" src="https://github.com/PROconsortium/PRoteinOntology/assets/50745/7e8868c2-5940-4b9a-8be3-0182bdeeb06b">

this is very confusing to a user, and although no ontology is ever complete (open world assumption), we should try to avoid creating grouping classes that lead to proliferation of incompleteness. See [open world considered harmful](https://douroucouli.wordpress.com/2020/09/04/the-open-world-assumption-considered-harmful/).
